export const clubCategories = [
	'all',
	'entertainment',
	'sports',
	'arts',
	'social',
	'food',
	'outdoor',
	'games',
];

export type ClubTags =
	| 'Dance'
	| 'Lessons'
	| 'Sports club'
	| 'Drop-in'
	| 'Crawl'
	| 'Pickeball'
	| 'Running'
	| 'Biking'
	| 'Climbing'
	| 'Basketball';

export const directoryData = [
	{
		name: 'Big Gay Night Toronto',
		description:
			'a concert series to showcase queer and trans musicians in toronto 🌈',
		instagram: 'biggaynight',
		website: '',
		category: 'entertainment',
		tags: 'music',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Breakfast Cycling Club',
		description:
			'WED Social Ride 615am —25 km/hr avg\nWomen, Trans, Non Binary ride Mon 6pm\n🚴🏽🚴🏽‍♀️ 🏳️‍🌈🏳️‍⚧️🇵🇸\nAnti-Zionist, Anti-oppressive',
		instagram: 'breakfastcycleclub',
		website: '',
		category: 'sports',
		tags: 'biking',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Butch/Femme Toronto',
		description:
			'Devoted to creating events and building community with and for Toronto’s femmes and butches',
		instagram: 'butchfemmetoronto',
		website: '',
		category: 'social',
		tags: 'meet ups, events',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Chill Queer Volleyball',
		description: '',
		instagram: 'chillqueervolleyball',
		website: '',
		category: 'sports',
		tags: 'volleyball, drop-in',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Field of Dreamers Cooperative Softball Association',
		description:
			"We're a small-scale cooperative softball league prioritizing queer, nonbinary, and lefty communities in Toronto 🌈 🥎",
		instagram: 'fieldofdreamerssoftball',
		website: 'https://fieldofdreamers.org/',
		category: 'sports',
		tags: 'softball, league',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Frontrunners Toronto',
		description: 'LGBTQ+ running club🏳️‍🌈🏳️‍⚧️🏃‍♀️🏃‍♂️',
		instagram: 'frontrunnerstoronto',
		website: 'https://www.frontrunnerstoronto.ca/',
		category: 'sports',
		tags: 'run club',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Learn Softball Toronto',
		description:
			'Beginner softball league & lessons for adult women, trans & non-binary players',
		instagram: 'learnsoftballto',
		website: '',
		category: 'sports',
		tags: 'softball, lessons',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Lesbian Film Society of Toronto',
		description:
			'Connecting the lesbian community, friends, & neighbours through a love for cinema.',
		instagram: 'lesbianfilmsocietytoronto',
		website: '',
		category: 'entertainment',
		tags: 'movies',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'NotsoAmazon Softball League',
		description:
			'Toronto softball for queer positive women, trans* & gender neutral individuals of all skill levels.',
		instagram: 'notsoamazon',
		website: 'http://www.notsoamazon.com/',
		category: 'sports',
		tags: 'softball, league',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Art Club Toronto',
		description:
			'Art Gallery Field Trips for Toronto Queers (18+)\nHosted by @meghansmusicstudio',
		instagram: 'queerartclub_toronto',
		website: '',
		category: 'arts',
		tags: 'art crawl',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Art Crawl',
		description:
			'A monthly walk club that highlights mural artists in Toronto. For 2SLGBTQIA+ and their allies.',
		instagram: 'queerartcrawl',
		website: '',
		category: 'arts',
		tags: 'art crawl',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Basketball TO',
		description:
			'We support & encourage strictly #bipoc & #lgbtq+ to come out🖤🌈',
		instagram: 'queerbasketballto',
		website: '',
		category: 'sports',
		tags: 'basketball',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Bike Club TO',
		description:
			'Welcome to the queer bike club of your\n🌟dreams🌟\nCollectively working towards facilitating a safe and fun (+cute) space for queers on bikes!',
		instagram: 'queerbikeclubto',
		website: '',
		category: 'sports',
		tags: 'biking',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Book Club Toronto',
		description:
			'🌈 All the gays | Reading all the 📚 \nNew members added a few times a year via a waitlist. Keep your eyes peeled for fun one-off events catered to the entire queer bookish community!',
		instagram: 'queerbookclubto',
		website: '',
		category: 'entertainment',
		tags: 'book club',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Cinema Club',
		description:
			'A queer film series at @paradiseonbloor curated & hosted by @peterknegt',
		instagram: 'queer.cinema.club',
		website: 'https://www.peterknegt.com/queercinemaclub',
		category: 'entertainment',
		tags: 'movies',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Climbers of Toronto',
		description:
			'A community to meet other queer and trans climbers in Toronto. Meetups on last Sunday of the month!',
		instagram: 'queerclimbto',
		website: '',
		category: 'sports',
		tags: 'climbing',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Coffee Toronto',
		description:
			'Focused on a space for women, trans, 2-spirit & non-binary people',
		instagram: 'queercoffeetoronto',
		website: '',
		category: 'food',
		tags: 'coffee',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Comedy Club TO',
		description:
			'Are you queer?🏳️‍🌈🏳️‍⚧️\nDo you love watching stand up comedy? Join the club! Come watch standup comedy with a bunch of queers who love to laugh! (19+)',
		instagram: 'queercomedyclubto',
		website: '',
		category: 'entertainment',
		tags: 'comedy club',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Crochet Cafe',
		description: "Let's set some time aside and crochet together",
		instagram: 'queercrochetcafe',
		website: '',
		category: 'arts',
		tags: 'crochet',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Euchre',
		description:
			'We’re here! We’re queer! We’re gonna play some euchre!\n•\nAll genders',
		instagram: 'queereuchre',
		website: '',
		category: 'games',
		tags: 'cards',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Foodies TO',
		description:
			'Street Festivals, Restaurants,\nPotlucks & more for 2SLGBTQ folks in Toronto! 🏳️‍🌈🏳️‍⚧️',
		instagram: 'queerfoodiesto',
		website: '',
		category: 'food',
		tags: 'food crawl',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Forest Club',
		description:
			"You ever met a tree you didn't like?\n(Inclusive group hikes in and around so-called Toronto)",
		instagram: 'queerforestclub',
		website: '',
		category: 'outdoor',
		tags: 'hikes',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Ice Skating Club Toronto',
		description: `Recreational skating meetups at Toronto's outdoor ice rinks`,
		instagram: 'queericeskatingtoronto',
		website: '',
		category: 'sports',
		tags: 'ice skating',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Mingle',
		description:
			"Meet ups and events dedicated to Toronto's lesbian, non-binary, trans and queer community!",
		instagram: 'queermingle',
		website: '',
		category: 'social',
		tags: 'meet ups, events',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Music Jam Toronto',
		description: 'A jam for women, NB and trans folx (ages 18+)',
		instagram: 'queermusicjam',
		website: 'https://sticksandpicks.com/queermusicjam/',
		category: 'arts',
		tags: 'music',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Photography Club',
		description:
			'A photography club for the 2SLGBTQIA+ community. Amateurs encouraged',
		instagram: 'queerphotographyclub',
		website: '',
		category: 'arts',
		tags: 'photography',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Pickleball Club',
		description:
			'This is a pickleball community for Queer women, Trans and Non-binary folk in Toronto! All levels welcome!',
		instagram: 'queerpickleballclub',
		website: 'https://queerpickleballclub.ca/',
		category: 'sports',
		tags: 'pickleball',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Pool Club',
		description: '',
		instagram: 'queerpoolclub.to',
		website: '',
		category: 'games',
		tags: 'pool',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Run Club',
		description:
			'Toronto queers run for fun. chill vibes. not serious. Centering women, trans, NB folks✌️🏳️‍⚧️🏳️‍🌈',
		instagram: 'queerrunclub',
		website: '',
		category: 'sports',
		tags: 'run club',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Skate Toronto',
		description:
			'A collective of skaters that aims to create safe spaces for queer people to learn and enjoy skateboarding in the Tkaronto area 🏳️‍🌈🏳️‍⚧️',
		instagram: 'queerskatetoronto',
		website: 'https://www.queerskatetoronto.com/',
		category: 'sports',
		tags: 'skateboard',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Sober Social',
		description:
			'A safe space for fellow sober or sober curious queers to attend events, create connections and build community! 🏳️‍🌈🏳‍⚧🌈',
		instagram: 'queer.sober.social',
		website: '',
		category: 'social',
		tags: 'meet ups, events',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Stitch Club',
		description:
			'Needlecraft, handicraft, and textile creation focused social club for queer folks in Toronto 🧶',
		instagram: 'queerstitchclubto',
		website: '',
		category: 'arts',
		tags: 'knit, crochet, embroidery',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Toronto Badminton Club',
		description: 'All queer folks are welcome.',
		instagram: 'queertorontobadmintonclub',
		website: '',
		category: 'sports',
		tags: 'badminton',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Toronto Film Club',
		description: '🍿🎬🎥🎭 Films, Theatre and Socials',
		instagram: 'queertorontofilmclub',
		website: '',
		category: 'entertainment',
		tags: 'movies',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer Wine Night',
		description:
			'🏳️‍🌈The official Queer Wine Night for the 2SLGBTQIA+ community, currently held in Toronto🏳️‍⚧️\n❤️‍🔥🍷❤️‍🔥',
		instagram: 'queerwinenight',
		website: '',
		category: 'food',
		tags: 'wine',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queery',
		description: 'trivia night for queer cuties 💞⛓️',
		instagram: 'thisisqueery',
		website: '',
		category: 'games',
		tags: 'trivia night',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Rainbow Hoops TO',
		description:
			'Toronto’s only OBA-registered & officiated recreational queer women’s basketball league.',
		instagram: 'rainbowhoopsto',
		website: 'https://www.rainbowhoops.ca/register',
		category: 'sports',
		tags: 'basketball',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'sparQ Runners',
		description:
			'Toronto Queer Run Crew. All Queers under the rainbow welcome 🏳️‍⚧️🏳️‍🌈',
		instagram: 'sparq.run',
		website: '',
		category: 'sports',
		tags: 'run club',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Spurs Night',
		description: 'Queer line dance',
		instagram: 'spursnight',
		website: '',
		category: 'entertainment',
		tags: 'dance, lessons',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Toronto Downtown Fastpitch League',
		description:
			'A new high level fastpitch league for women, trans, and non-binary players. Wanna learn more?',
		instagram: 'tdfl_fastpitch',
		website: 'https://torontodowntownfastpitch.ca/',
		category: 'sports',
		tags: 'softball, league',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Toronto Gay Pickleball',
		description: '',
		instagram: 'togaypickleball',
		website: 'https://www.tgpa.ca/',
		category: 'sports',
		tags: 'pickleball',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Toronto Queer Bike Polo',
		description:
			'A space for queer folks to learn and practice hardcourt bike polo',
		instagram: 'torontoqueerbikepolo',
		website: '',
		category: 'sports',
		tags: 'bike polo',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Toronto Queer Competitive Solo Napping Club',
		description:
			'This club is for queer folx in the GTA who love napping and want to meet other like minded folk serious about solo naps',
		instagram: 'torontoqueernappers',
		website: '',
		category: 'social',
		tags: 'napping',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Toronto Queer Swim Club',
		description: 'Toronto based swim club for gender diverse folks',
		instagram: 'toqueer_swimclub',
		website: 'https://www.torontoqueerswimclub.ca/',
		category: 'sports',
		tags: 'swimming',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'West End Queer Dog Club',
		description:
			'A place for queer dog owners to meet in the west end of Toronto. Dog parks, walks, hikes, park hangs! 🏳️‍🌈🏳️‍⚧️🐶🐾',
		instagram: 'westendqueerdogclub',
		website: '',
		category: 'social',
		tags: 'dogs',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Chaotic Queer Dodgeball',
		description:
			'Drop-in Toronto dodgeball for queer folks that are marginalized genders on Wednesday nights 7-9p - It’s chaotic',
		instagram: 'chaoticqueerdodgeball',
		website: '',
		category: 'sports',
		tags: 'dodgeball, drop-in',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'sqwish',
		description:
			'🏀 Toronto-based queer drop-in basketball night\n📍 Central Technical School\n⏰ Fridays 6-8PM\n👨‍👨‍👦 Run by @aminaformayor, @microsoft_orifice and @emmerek',
		instagram: 'sqwishsqwish',
		website: '',
		category: 'sports',
		tags: 'basketball, drop-in',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Toronto Purple Fins',
		description:
			'Gender Free Swim Club\nLeading 2STGNC+ Inclusion in Canadian Swimming\n🏳️‍⚧️ We Nurture Community & Promote Education\n2 Weekly Practices',
		instagram: 'purplefinsto',
		website: 'https://www.torontopurplefins.com/',
		category: 'sports',
		tags: 'swimming',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: "Women's Hockey Club of Toronto",
		description:
			'Toronto’s trans and non-binary inclusive hockey league for queer and allied women. Since 1993.',
		instagram: 'whctmosspark',
		website: 'http://whct.ca/',
		category: 'sports',
		tags: 'hockey',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Ok Dodgeball Club',
		description:
			'74 Wellesley St. W Upper Gym | Doors @ 6:30\nA more competitive league for women, trans and non-binary folk who are pretty okay at dodgeball!',
		instagram: 'ok_dodgeball_club',
		website: '',
		category: 'sports',
		tags: 'dodgeball, league',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Pink Turf Soccer League',
		description:
			'Toronto’s adult non-profit women and trans soccer league - open to the 2SLGBTQ+ community & allies since 1985 🏳️‍🌈🏳️‍⚧️⚽️',
		instagram: 'pinkturfsoccer',
		website: 'https://www.pinkturfsoccer.com/',
		category: 'sports',
		tags: 'soccer, league',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Flags of Glory Toronto 🏈',
		description:
			'Toronto’s Queer Flag football league welcoming all queer positive women, trans, and non-binary players. (18+)🏳️‍🌈 🏳️‍⚧️🌈',
		instagram: 'flagsofgloryto',
		website: 'http://flagsofglory.com/home/',
		category: 'sports',
		tags: 'football, league',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-17-2024',
	},
	{
		name: 'Queer South Asian Women’s Network',
		description:
			'Hosts events virtually and in-person to connect and visibilize diasporic LGBTQ+ women, trans, & nonbinary South Asians',
		instagram: 'qsawnetwork',
		website: 'https://www.qsawnetwork.com',
		category: 'social',
		tags: 'meet ups, events',
		location: 'Varies',
		when: 'Varies',
		paid: 'Sometimes paid',
		dateAdded: '05-18-2024',
	},
	{
		name: "Que'd Up",
		description: 'Toronto collective supporting LGBTQ+ DJs',
		instagram: 'quedup_toronto',
		website: '',
		category: 'social',
		tags: 'meet ups, events',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-20-2024',
	},
	{
		name: 'Queer Healing Collective',
		description:
			'Blending wellness, education, conversation & play. Where all intersections of queer identity can be deeply introspective and delightfully silly 🌈✨',
		instagram: 'queerhealingto',
		website: '',
		category: 'social',
		tags: 'mental health, wellness',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-20-2024',
	},
	{
		name: 'TOASTR Toronto',
		description: 'Events in Toronto that include lesbianism and the like.',
		instagram: 'toastrto',
		website: '',
		category: 'social',
		tags: 'meet ups, events',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-20-2024',
	},
	{
		name: 'Bulges & Boulders',
		description:
			'A community of 2SLGBTQ+ climbers in Toronto. Open to all genders, orientations and skill levels. Weekly Tue at Rock Oasis/Joe R (last Tue of a month)',
		instagram: 'bulgesandboulders',
		website: '',
		category: 'sports',
		tags: 'climbing',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-20-2024',
	},
	{
		name: 'Yohomo',
		description:
			"Toronto's only online community completely dedicated to the arts, culture, and nightlife of our beautiful LGBTQ2+ family.",
		instagram: 'weareyohomo',
		website: 'https://www.yohomo.ca/',
		category: 'social',
		tags: 'meet ups, events',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-20-2024',
	},
	{
		name: 'STRAPS',
		description: 'real tuff queer arm wrestling in Toronto',
		instagram: 'strapsarmwrestling',
		website: '',
		category: 'sports',
		tags: 'arm wrestling',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-20-2024',
	},
	{
		name: 'Toronto Spartan Volleyball',
		description:
			'We are a non-profit adult LGBTQ+ volleyball league. We offer a fun, safe space to play a sport we love.',
		instagram: 'tsvl_insta',
		website: '',
		category: 'sports',
		tags: 'volleyball, league',
		location: '',
		when: '',
		paid: '',
		dateAdded: '05-20-2024',
	},
];
