export const clubCategories = [
	'all',
	'entertainment',
	'sports',
	'arts',
	'social',
	'food',
	'outdoor',
];

export type ClubTags =
	| 'Dance'
	| 'Lessons'
	| 'Sports club'
	| 'Drop-in'
	| 'Crawl'
	| 'Pickeball'
	| 'Running'
	| 'Biking'
	| 'Climbing'
	| 'Basketball';

export const directoryData = [
	{
		name: 'Spurs night',
		description: 'Queer line dance',
		instagram: 'spursnight',
		category: 'entertainment',
		tags: ['Dance', 'Lessons'],
		location: 'Owls club',
		when: 'Sundays at 7:30pm',
		paid: '',
	},
	{
		name: 'Queer run club',
		description:
			'Toronto queers run for fun. chill vibes. not serious. Centering women, trans, NB folks✌️🏳️‍⚧️🏳️‍🌈',
		instagram: 'queerrunclub',
		category: 'sports',
		tags: ['Run club'],
		location: 'Ethica',
		when: 'Saturdays at 9:20am',
		paid: 'No',
	},
	{
		name: 'Queer mingle',
		description:
			"Meet ups and events dedicated to Toronto's lesbian, non-binary, trans and queer community!",
		instagram: 'queermingle',
		category: 'social',
		tags: ['Meet ups', 'Events'],
		location: 'Varies',
		when: 'Varies',
		paid: '',
	},
	{
		name: 'Queer Toronto Film Club',
		description: '🍿🎬🎥🎭 Films, Theatre and Socials',
		instagram: 'queertorontofilmclub',
		category: 'entertainment',
		tags: ['Movies'],
		location: 'Varies',
		when: 'Varies',
		paid: '',
	},
	{
		name: 'Queer Toronto Badminton Club',
		description: 'All queer folks are welcome.',
		instagram: 'queertorontobadmintonclub',
		category: 'sports',
		tags: ['Badminton'],
		location: 'Scadding Community Centre',
		when: 'Every sunday',
		paid: 'Yes, must RSVP',
	},
	{
		name: 'Queer coffee toronto',
		description:
			'Focused on a space for women, trans, 2-spirit & non-binary people',
		instagram: 'queercoffeetoronto',
		category: 'food',
		tags: ['Coffee'],
		location: 'Varies',
		when: 'Sundays',
		paid: '',
	},
	{
		name: 'Queer stitch club',
		description:
			'Needlecraft, handicraft, and textile creation focused social club for queer folks in Toronto 🧶',
		instagram: 'queerstitchclubto',
		category: 'arts',
		tags: ['Knit', 'Crochet', 'Embroidery'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Learn Softball Toronto',
		description:
			'Beginner softball league & lessons for adult women, trans & non-binary players',
		instagram: 'learnsoftballto',
		category: 'sports',
		tags: ['Softball'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Field of Dreamers Cooperative Softball Association',
		description:
			"We're a small-scale cooperative softball league prioritizing queer, nonbinary, and lefty communities in Toronto 🌈 🥎",
		instagram: 'fieldofdreamerssoftball',
		category: 'sports',
		tags: ['Softball'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Chill queer volleyball',
		description: '',
		instagram: 'chillqueervolleyball',
		category: 'sports',
		tags: ['Volleyball', 'Drop-in'],
		location: 'Trinity Bellwoods',
		when: '',
		paid: '',
	},
	{
		name: 'sparQ runners',
		description:
			'Toronto Queer Run Crew. All Queers under the rainbow welcome 🏳️‍⚧️🏳️‍🌈',
		instagram: 'sparq.run',
		category: 'sports',
		tags: ['Run club'],
		location: 'Varies',
		when: 'Thursdays at 7pm',
		paid: 'No',
	},
	{
		name: 'Frontrunners Toronto',
		description: 'LGBTQ+ running club🏳️‍🌈🏳️‍⚧️🏃‍♀️🏃‍♂️',
		instagram: 'frontrunnerstoronto',
		category: 'sports',
		tags: ['Run club'],
		location: 'Varies',
		when: 'Tuesdays and Thursdays 6:15PM',
		paid: '',
	},
	{
		name: 'Queer cinema club',
		description:
			'A queer film series at @paradiseonbloor curated & hosted by @peterknegt',
		instagram: 'queer.cinema.club',
		category: 'entertainment',
		tags: ['Movies'],
		location: 'Paradise on bloor',
		when: 'Varies',
		paid: '',
	},
	{
		name: 'Queer forest club',
		description:
			"You ever met a tree you didn't like?\n(Inclusive group hikes in and around so-called Toronto)",
		instagram: 'queerforestclub',
		category: 'outdoor',
		tags: ['Hiking'],
		location: 'Varies',
		when: 'Varies',
		paid: '',
	},
	{
		name: 'Queer Foodies TO',
		description:
			'Street Festivals, Restaurants,\nPotlucks & more for 2SLGBTQ folks in Toronto! 🏳️‍🌈🏳️‍⚧️',
		instagram: 'queerfoodiesto',
		category: 'food',
		tags: ['Food crawl'],
		location: 'Varies',
		when: 'Varies',
		paid: '',
	},
	{
		name: 'Queer Climbers of Toronto',
		description:
			'A community to meet other queer and trans climbers in Toronto. Meetups on last Sunday of the month!',
		instagram: 'queerclimbto',
		category: 'sports',
		tags: ['Climbing'],
		location: 'Basecamp Bloor West',
		when: 'Last sunday of the month',
		paid: '',
	},
	{
		name: 'Queer Bike Club TO',
		description:
			'Welcome to the queer bike club of your\n🌟dreams🌟\nCollectively working towards facilitating a safe and fun (+cute) space for queers on bikes!',
		instagram: 'queerbikeclubto',
		category: 'sports',
		tags: ['Biking'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queery',
		description: 'trivia night for queer cuties 💞⛓️',
		instagram: 'thisisqueery',
		category: 'entertainment',
		tags: ['Trivia night'],
		location: 'Three dollar bill parkdale',
		when: '',
		paid: '',
	},
	{
		name: 'Big Gay Night Toronto',
		description:
			'a concert series to showcase queer and trans musicians in toronto 🌈',
		instagram: 'biggaynight',
		category: 'entertainment',
		tags: ['Music'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer Book Club Toronto',
		description: '🌈 All the gays | Reading all the 📚',
		instagram: 'queerbookclubto',
		category: 'entertainment',
		tags: ['Book club'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer Pickleball Club',
		description:
			'This is a pickleball community for Queer women, Trans and Non-binary folk in Toronto! All levels welcome!',
		instagram: 'queerpickleballclub',
		category: 'sports',
		tags: ['Pickleball'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Toronto Queer Swim Club',
		description: 'Toronto based swim club for gender diverse folks',
		instagram: 'toqueer_swimclub',
		category: 'sports',
		tags: ['Swimming'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer Ice Skating Club Toronto',
		description:
			'A group for queer people and friends to enjoy the outdoor ice rinks of the city of Toronto together',
		instagram: 'queericeskatingtoronto',
		category: 'sports',
		tags: ['Ice Skating'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Toronto Gay Pickleball',
		description: '',
		instagram: 'togaypickleball',
		category: 'sports',
		tags: ['Pickleball'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'West End Queer Dog Club',
		description:
			'A place for queer dog owners to meet in the west end of Toronto. Dog parks, walks, hikes, park hangs! 🏳️‍🌈🏳️‍⚧️🐶🐾',
		instagram: 'westendqueerdogclub',
		category: 'social',
		tags: ['Dogs'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer Comedy Club TO',
		description:
			'Are you queer?🏳️‍🌈🏳️‍⚧️\nDo you love watching stand up comedy? Join the club! Come watch standup comedy with a bunch of queers who love to laugh! (19+)',
		instagram: 'queercomedyclubto',
		category: 'entertainment',
		tags: ['Comedy club'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Lesbian Film Society of Toronto',
		description:
			'Connecting the lesbian community, friends, & neighbours through a love for cinema.',
		instagram: 'lesbianfilmsocietytoronto',
		category: 'entertainment',
		tags: ['Movies'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer basketball TO',
		description:
			'We support & encourage strictly #bipoc & #lgbtq+ to come out🖤🌈',
		instagram: 'queerbasketballto',
		category: 'sports',
		tags: ['Basketball'],
		location: 'Christie Pits',
		when: 'Wednesdays at 7pm',
		paid: '',
	},
	{
		name: 'Queer Photography Club',
		description:
			'A photography club for the 2SLGBTQIA+ community. Amateurs encouraged',
		instagram: 'queerphotographyclub',
		category: 'arts',
		tags: ['Photography'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer Art Crawl',
		description:
			'A monthly walk club that highlights mural artists in Toronto. For 2SLGBTQIA+ and their allies.',
		instagram: 'queerartcrawl',
		category: 'arts',
		tags: ['Art crawl'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer Crochet Cafe',
		description: "Let's set some time aside and crochet together",
		instagram: 'queercrochetcafe',
		category: 'arts',
		tags: ['Crochet'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Butch/Femme Toronto',
		description:
			'Devoted to creating events and building community with and for Toronto’s femmes and butches',
		instagram: 'butchfemmetoronto',
		category: 'social',
		tags: ['Meet ups', 'Events'],
		location: '',
		when: '',
		paid: '',
	},
	{
		name: 'Queer Sober social',
		description:
			'A safe space for fellow sober or sober curious queers to attend events, create connections and build community! 🏳️‍🌈🏳‍⚧🌈',
		instagram: 'queer.sober.social',
		category: 'social',
		tags: ['Meet ups', 'Events'],
		location: '',
		when: '',
		paid: '',
	},
];
